docs: Modify wait_limit option of batch-run command
Magic-Pod/magicpod-api-client pull request #6
Opened 2023-06-21 04:19 UTC by gkzz

### Motivation
I'd like to share with you that you can also make a use of `wait_limit` option, when using the `wait` command to wait for the `./magicpod-api-client batch-run` command to finish.

### What I changed
I added an example of the `wait_limit` option.

Ref. https://github.com/Magic-Pod/magicpod-api-client/blob/beb27eebd35222cfd55c779fba324bf505dc11d1/magicpod-api-client.go#L43-L45

### What I checked
Checked manually if comparing the output of `./magicpod-api-client batch-run --help` command.

2023-06-23 04:57 UTC, nkns165 requested changes
Thank you for your contribution again, I have two requests.

2023-06-23 04:57 UTC, nkns165 commented on README.md
> +You can also specify the wait limit in seconds. If execution time of your [BatchRun/CrossBatchRun](https://magic-pod.com/api/v1.0/doc/) is expected to exceed the initial value of 300 seconds, it woul
I'm afraid `magic-pod.com` is our old domain. Could you replace it with `app.magicpod.com`?
We already know the redirection from https://magic-pod.com/api/v1.0/doc/ to https://app.magicpod.com/api/v1.0/doc/ is not working while it works on other URLs, and consider it should be fixed on our side in the future.
Sorry for the inconvenience.

2023-06-23 04:57 UTC, nkns165 commented on README.md
> +You can also specify the wait limit in seconds. If execution time of your [BatchRun/CrossBatchRun](https://magic-pod.com/api/v1.0/doc/) is expected to exceed the initial value of 300 seconds, it woul
It seems the default value 300 seconds is for another command `get-screenshots`.
The waiting time for `batch-run` is `test count x 10 minutes` as you mentioned.
Could you please replace the description?

2023-06-24 14:16 UTC, gkzz commented on README.md
> +You can also specify the wait limit in seconds. If execution time of your [BatchRun/CrossBatchRun](https://magic-pod.com/api/v1.0/doc/) is expected to exceed the initial value of 300 seconds, it woul
Thank you for your kindness!
I applied your feedback, https://github.com/Magic-Pod/magicpod-api-client/pull/6/commits/7759c22789590dc4420f8f6c1cdd8c71152577c7

I'll rebase it, if everything is ok :)

2023-06-26 00:06 UTC, nkns165 commented on README.md
> +You can also specify the wait limit in seconds. If execution time of your [BatchRun/CrossBatchRun](https://magic-pod.com/api/v1.0/doc/) is expected to exceed the initial value of 300 seconds, it woul
Thank you for your fix!
Sorry, I have told you a wrong comment in the previous pull request.
We usually do `squash and merge`, not `rebase and merge`. By `squash and merge`, all changes are gathered into one commit on the main branch. So you don't need to rebase the commits in the pull request.

2023-06-26 00:07 UTC, nkns165 approved these changes

2023-06-26 04:45 UTC, gkzz commented on README.md
> +You can also specify the wait limit in seconds. If execution time of your [BatchRun/CrossBatchRun](https://magic-pod.com/api/v1.0/doc/) is expected to exceed the initial value of 300 seconds, it woul
I got it.
I've completed it, https://github.com/Magic-Pod/magicpod-api-client/pull/6/commits/18205dab4dbf51d1d7c9f48925b3423123e48aa7

2023-06-26 04:47 UTC, merged